import sys
import os
import urllib.parse
import pandas as pd
import requests
import datetime
import json
from sqlalchemy import create_engine, text

# Add current dir to path for imports
sys.path.append(os.path.dirname(__file__))
import telegram_helper

# Configuration
DEFAULT_SERVER = "192.168.1.205"
DB_NAME = "carmal_a"
OLLAMA_HOST = "http://192.168.1.79:11434"
MODEL = "llama3"

# SQL Queries
QUERY_AUDIT = """
SELECT 
    a.co_art, a.art_des, a.stock_min,
    ISNULL(SUM(l.stock_actual), 0) AS total_lotes,
    (a.stock_min - ISNULL(SUM(l.stock_actual), 0)) AS descuadre
FROM saArticulo a
LEFT JOIN saLoteEntrada l ON a.co_art = l.co_art
WHERE a.maneja_lote = 1
GROUP BY a.co_art, a.art_des, a.stock_min
HAVING a.stock_min <> ISNULL(SUM(l.stock_actual), 0);
"""

QUERY_PURCHASING = """
SELECT 
    f.co_art AS materia_prima,
    SUM(r.total_art * f.cantidad) AS consumo_proyectado,
    ((SUM(r.total_art * f.cantidad) * 1.30)) AS meta_con_reserva
FROM carmal_a.dbo.saFacturaVentaReng r
JOIN carmal_m.dbo.NSPFormulareng f ON r.co_art COLLATE DATABASE_DEFAULT = f.co_art COLLATE DATABASE_DEFAULT
WHERE r.fe_us_in >= DATEADD(month, -1, GETDATE())
GROUP BY f.co_art;
"""

SYSTEM_PROMPT = """
Analiza los datos de Profit Plus. 
Si ves descuadres (Audit Data), sugiere un código de motivo para lam tabla saAjuste (ej: 'AJ-INV-AUD').
Si el stock de materia prima proyectado es menor a la 'meta_con_reserva' (Purchasing Data), redacta una lista de compras urgente indicando el código de artículo (co_art) de saArticulo. 
Mantén un tono ejecutivo y directo.
"""

def get_engine():
    driver = "ODBC Driver 17 for SQL Server"
    base_conn = (
        f"DRIVER={{{driver}}};"
        f"SERVER={DEFAULT_SERVER};"
        f"DATABASE={DB_NAME};"
        "UID=PROFIT;"
        "PWD=profit;"
        "Encrypt=yes;"
        "TrustServerCertificate=yes;"
    )
    params = urllib.parse.quote_plus(base_conn)
    url = f"mssql+pyodbc:///?odbc_connect={params}"
    return create_engine(url)

def get_data(engine, query, name):
    print(f"Executing {name} Query...")
    try:
        df = pd.read_sql_query(text(query), engine)
        return df
    except Exception as e:
        print(f"Error in {name}: {e}")
        return pd.DataFrame()

def analyze_with_ai(audit_df, purchasing_df):
    
    # Prepare data context
    audit_str = "SIN DESCUADRES"
    if not audit_df.empty:
        audit_str = audit_df.to_markdown(index=False)
        
    purch_str = "SIN REQUERIMIENTOS"
    if not purchasing_df.empty:
        purch_str = purchasing_df.head(10).to_markdown(index=False) # Limit to top 10 for prompt context limits

    full_prompt = f"{SYSTEM_PROMPT}\n\n--- AUDIT DATA (Inconsistencies) ---\n{audit_str}\n\n--- PURCHASING DATA (Material Explosion) ---\n{purch_str}"
    
    print(f"Sending to AI ({OLLAMA_HOST})...")
    
    try:
        response = requests.post(
            f"{OLLAMA_HOST}/api/generate",
            json={"model": MODEL, "prompt": full_prompt, "stream": False},
            timeout=10 # Short timeout for quick failover
        )
        if response.status_code == 200:
            return response.json().get('response', '')
    except:
        print("AI Unreachable. Using Fallback Logic...")
        return None

def fallback_analysis(audit_df, purchasing_df):
    report = "# Informe Ejecutivo (Generado por Sistema de Respaldo)\n\n"
    
    # Audit Section
    report += "## 1. Auditoría de Inventario (Riesgos)\n"
    if audit_df.empty:
        report += "✅ No se encontraron inconsistencias en los lotes.\n"
    else:
        for _, row in audit_df.iterrows():
            report += f"- **{row['art_des']} ({row['co_art']})**: Descuadre de **{row['descuadre']}** unidades. (Lotes: {row['total_lotes']} vs Min: {row['stock_min']})\n"
    
    # Purchasing Section
    report += "\n## 2. Planificación de Compras (Meta +30%)\n"
    if purchasing_df.empty:
        report += "ℹ️ No hay data de ventas reciente para proyectar consumo.\n"
    else:
        for _, row in purchasing_df.iterrows():
            report += f"- **{row['materia_prima']}**: Consumo Proyectado **{row['consumo_proyectado']:.2f}**. Meta con Reserva: **{row['meta_con_reserva']:.2f}**.\n"
            
    return report

def generate_sql_adjustments(audit_df):
    sql_script = "-- SQL Adjustments generated by Super-Workflow\n-- Review before executing\n\n"
    
    if audit_df.empty:
        sql_script += "-- No adjustments needed."
    else:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        sql_script += f"/* Generated at {timestamp} */\n"
        
        # Header (Hypothetical saAjuste structure - simplified)
        sql_script += "INSERT INTO saAjuste (co_tipo, co_inv, fecha, motivo_glo) VALUES ('AJ-SAL', '01', GETDATE(), 'AJUSTE AUDITORIA AUTOMATICA');\n\n"
        
        for i, row in audit_df.iterrows():
            # Detail (Hypothetical saAjusteReng)
            qty = row['descuadre']
            # Only negative adjustments logic for 'missing' stock usually means an 'Output' adjustment
            # Here we assume positive descuadre means we are missing physical stock (Admin > Lote)
            sql_script += f"INSERT INTO saAjusteReng (co_art, total_art, tipo) VALUES ('{row['co_art']}', {qty}, 'SALIDA'); -- Faltante detected\n"
            
    return sql_script

def check_alerts(audit_df):
    alerts = []
    if audit_df.empty:
        return

    for _, row in audit_df.iterrows():
        stock_min = row['stock_min']
        descuadre = abs(row['descuadre'])
        
        if stock_min > 0:
            percentage = descuadre / stock_min
            if percentage > 0.05: # 5% Threshold
                alerts.append(f"CRITICO: {row['art_des']} ({row['co_art']}) - Descuadre {percentage:.1%} ({descuadre}/{stock_min})")
        elif descuadre > 0:
             # Infinite percentage error (Min is 0, but there is a discrepancy)
             alerts.append(f"CRITICO: {row['art_des']} ({row['co_art']}) - Descuadre INFINITO ({descuadre}/0.0)")
    
    if alerts:
        docs_dir = os.path.join(os.path.dirname(__file__), '..', 'docs')
        os.makedirs(docs_dir, exist_ok=True)
        alert_path = os.path.join(docs_dir, 'ALERTA_AUDITORIA_URGENTE.txt')
        
        content = "⚠️ REVISION URGENTE REQUERIDA (Descuadre > 5%) ⚠️\n\n"
        content += "\n".join(alerts)
        content += "\n\nAccion: Revisar reporte ejecutivo y aprobar ajustes en SQL."
        
        with open(alert_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"ALERT GENERATED: {alert_path}")
        
        # Also copy to Downloads for visibility
        try:
            import shutil
            user_profile = os.environ.get('USERPROFILE')
            if user_profile:
                dest = os.path.join(user_profile, 'Downloads', 'ALERTA_AUDITORIA_URGENTE.txt')
                shutil.copy(alert_path, dest)
                print(f"Alert copied to Downloads: {dest}")
        except Exception as e:
            print(f"Could not copy alert to downloads: {e}")
            
        # TELEGRAM ALERT
        try:
            telegram_helper.send_message(f"🚨 *ALERTA CRITICA PROFIT PLUS* 🚨\n\nSe han detectado descuadres > 5% en la auditoria de inventario.\n\nPor favor revise el archivo:\n`Downloads/ALERTA_AUDITORIA_URGENTE.txt`")
        except Exception as e:
            print(f"Failed to send Telegram Alert: {e}")

def run():
    print("--- Starting Super-Workflow ---")
    
    engine = get_engine()
    
    # 1. Fetch Data
    audit_df = get_data(engine, QUERY_AUDIT, "Audit")
    purchasing_df = get_data(engine, QUERY_PURCHASING, "Purchasing")
    
    # 2. Alerts (Priority Check)
    check_alerts(audit_df)
    
    # 3. Intelligence
    analysis_text = analyze_with_ai(audit_df, purchasing_df)
    
    if not analysis_text:
        analysis_text = fallback_analysis(audit_df, purchasing_df)
        
    # TELEGRAM REPORT
    try:
        # Extract summary for Telegram (First 1000 chars)
        summary = analysis_text[:1000] + "..." if len(analysis_text) > 1000 else analysis_text
        telegram_helper.send_message(f"📊 *Reporte Ejecutivo Generado* (Bot: Belen)\n\n{summary}")
    except Exception as e:
        print(f"Failed to send Telegram Report: {e}")
    
    # 4. Output Generation
    docs_dir = os.path.join(os.path.dirname(__file__), '..', 'docs')
    os.makedirs(docs_dir, exist_ok=True)
    
    # Report
    report_path = os.path.join(docs_dir, 'executive_report.md')
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(analysis_text)
    print(f"Report saved: {report_path}")
    
    # SQL
    sql_path = os.path.join(docs_dir, 'proposed_adjustments.sql')
    sql_content = generate_sql_adjustments(audit_df)
    with open(sql_path, 'w', encoding='utf-8') as f:
        f.write(sql_content)
    print(f"SQL saved: {sql_path}")

    # JSON Data for Web Dashboard
    json_path = os.path.join(docs_dir, 'latest_results.json')
    dashboard_data = {
        "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "audit_data": audit_df.to_dict(orient='records'),
        "purchasing_data": purchasing_df.to_dict(orient='records'),
        "summary": analysis_text
    }
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(dashboard_data, f, indent=4, default=str)
    print(f"JSON Data saved: {json_path}") 

if __name__ == "__main__":
    run()
